services:
  mongo1:
    image: mongo:8.0
    container_name: mongo1
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=mydb
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mypassword
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  tabix:
      image: spoonest/clickhouse-tabix-web-client:latest
      container_name: tabix
      ports:
        - "8080:8080"
      environment:
        - CLICKHOUSE_HOST=clickhouse
        - CLICKHOUSE_PORT=8123
        - CLICKHOUSE_USER=default
        - CLICKHOUSE_PASSWORD=mypassword
      depends_on:
        - clickhouse

volumes:
  mongo1_data:
  mongo1_config:
  clickhouse_data: